[workspace]
authors = ["JarningGau <jarninggau@gmail.com>"]
channels = ["https://mirrors2.westlake.edu.cn/ANACONDA/cloud/conda-forge", "https://mirrors2.westlake.edu.cn/ANACONDA/cloud/bioconda"]
name = "seeksoul-matrix"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fastp-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --skip-workdir-input-checks --dry-run"
demux-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage demux_extract_bc --skip-workdir-input-checks --dry-run"
regroup-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage regroup_shards --skip-workdir-input-checks --dry-run"
bismark-align-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage bismark_align --skip-workdir-input-checks --dry-run"
bam-sort-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage bam_sort --skip-workdir-input-checks --dry-run"
count-mapped-reads-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage count_mapped_reads --skip-workdir-input-checks --dry-run"
estimated-cells-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage estimated_cells --skip-workdir-input-checks --dry-run"
split-bams-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage split_bams --skip-workdir-input-checks --dry-run"
merge-fr-bams-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage merge_fr_bams --skip-workdir-input-checks --dry-run"
bam-to-allc-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage bam_to_allc --skip-workdir-input-checks --dry-run"
saturation-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage saturation --skip-workdir-input-checks --dry-run"
qc-summary-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage qc_summary --skip-workdir-input-checks --dry-run"
e2e-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage all --dry-run"
e2e-slurm-dry-run = "python scripts/make_cmd.py --workflow-config workflow/dd_met5_test.json --stage all --runner slurm --dry-run"
setup-bismark = "bash scripts/install_seekgene_bismark.sh"
check-bismark-env = "bash scripts/check_bismark_env.sh"
setup-allcools = "bash scripts/install_seekgene_allcools.sh"
check-allcools-env = "bash scripts/check_allcools_env.sh"

[dependencies]
python = "3.11.*"
pip = "*"
fastp = "0.24.*"
tqdm = ">=4.66,<5"
cutadapt = "5.0.*"
bowtie2 = "2.5.*"
htslib = ">=1.21,<2"
samtools = ">=1.21,<2"
pysam = ">=0.22,<1"
perl = "5.32.*"
git = "*"
bedtools = ">=2.31.1,<3"
matplotlib = ">=3.10,<4"
